# Generated by Django 5.2.4 on 2025-08-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_vat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='net_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='net_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
