# Generated by Django 5.2.4 on 2025-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderitem_net_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='net_unit_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_amount',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='net_subtotal',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_subtotal',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True),
        ),
    ]
